version: "3"

services:

  test-orchestrator-root-config:
    #    image: test-orchestrator-root-config
    build: .

    #    depends_on:
    #      - teiler-core
    ports:
      - 9000:9000
    environment:
      TEILER_CORE_URL: "http://localhost:8085"
      TEILER_UI_URL: "http://localhost:4200"
      DEFAULT_LANGUAGE: "de"
      TEILER_ROOT_CONFIG_SERVER_NAME: "localhost"

#  teiler-core :
#    image: teiler-core
