version: "3"

services:

  test-orchestrator-root-config:
    #    image: test-orchestrator-root-config
    build: .

    #    depends_on:
    #      - teiler-core
    ports:
      - 9000:9000
    environment:
      TEILER_CORE_URL: "http://host.docker.internal:8085"
      TEILER_UI_URL: "http://host.docker.internal:4200"

#  teiler-core :
#    image: teiler-core
